# Generated by Django 5.2.4 on 2025-07-07 08:31

import django.core.validators
from django.db import migrations, models

import education.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EducationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        unique=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Порядковый номер",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200,
                        validators=[django.core.validators.MinLengthValidator(5)],
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        validators=[education.models.MinLengthValidator(3)],
                        verbose_name="Описание",
                    ),
                ),
            ],
            options={
                "verbose_name": "Образовательный модуль",
                "verbose_name_plural": "Образовательные модули",
                "ordering": ["order"],
            },
        ),
    ]
